name: CI
on:
  push:
    branches:
      - main
      - r[1-9]
  pull_request:
    branches:
      - main
      - r[1-9]
jobs:
  build-and-push-nebulous-forecast-ensembler:
    name: Build and push forecast-ensembler
    uses: eu-nebulous/github-actions/.github/workflows/build-and-push-container-image.yml@main
    with:
      context: ensembler
      image-name: nebulous-forecast-ensembler
    secrets: inherit